using UnityEngine.InputSystem;
using UnityEngine;

public class PlayerTag : MonoBehaviour
{
    [SerializeField] private GameObject nano;
    [SerializeField] private GameObject tera;
    bool isnano = false;
    bool istera = false;
    void Start()
    {
        //nano = GameObject.Find("player_nano");
        //tera = GameObject.Find("player_tera");

        nano.SetActive(true);
        isnano = true;
        tera.SetActive(false);
    }

    public void OnTagKey(InputValue value)
    {

        if (!value.isPressed) return;

        Debug.Log(" Z ¹öÆ° ´­¸²! ");

        if (isnano)
        {
            tera.SetActive(true);
            nano.SetActive(false);
            isnano = false;
            istera = true;
        }

        else if (istera)
        {
            tera.SetActive(false);
            nano.SetActive(true);
            isnano = true;
            istera = false;
        }

    }
    void Update()
    {

    }
}
