/*using System;
using System.Collections;
using System.Collections.Generic;
using UnityEditor.U2D.Animation;
using UnityEngine;
using UnityEngine.PlayerLoop;


[System.Serializable]
public class MobStat
{

    [SerializeField] private float baseValue;

    private float _value;
    private bool _isChange = true;

    private List<float> modifiers = new List<float>();

    public MobStat(float baseValue)
    {
        this.baseValue = baseValue;
    }
    private float CalculStat()
    {
        float finalValue = baseValue;
        foreach(float m in modifiers)
        {
            _value += m;
        }
        return finalValue; 
    }
    public float fvalue
    {
        get { return fvalue; }
    }
    public int ivalue
    {
        get { return ivalue; }
    }
}
public class MobBase : MonoBehaviour
{
    [Header("Character Data")]
    [SerializeField] private EnemyStat enemyStat;
    public MobStat MaxSpeed;
    public MobStat JumpPower;
    public MobStat MaxJumpCount;
    public MobStat Hp;
    void Awake()
    {
        if (enemyStat == null)
        {
            Debug.LogError("Character Data가 할당되지 않았습니다!");
        }
        else
        {
            InitializeStat();
        }
    }
    public void InitializeStat()
    {
        MaxSpeed = new MobStat(enemyStat.playerMaxSpeed);
        JumpPower = new MobStat(enemyStat.playerJumpPower);
        MaxJumpCount = new MobStat(enemyStat.playerMaxJumpCount);
        Hp = new MobStat(enemyStat.playerHp);
    }
}*/
